version: '3'
volumes: 
  dados:  
services: 
  db: 
    image: postgres:9.6
    volumes: 
      # volumes dos dados
      - dados:/var/lib/postgresql/data
      # volumes dos scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql